# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
author:
  name             : "Szilvia Ujváry"
  avatar           : "szilvia_ujvary_photo.jpg"
  bio              : "ML PhD student @ Cambridge"
  location         : "Cambridge, UK"
  employer         :
  pubmed           :
  googlescholar    : 
  email            :
  email            : "sru23@cam.ac.uk"
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
